from __future__ import annotations

import pandas as pd

from market_prediction_agent.reporting.builders import build_evidence_bundle, build_forecast_output, build_report_payload, build_risk_review
from market_prediction_agent.schemas.validator import validate_payload


def test_output_payloads_match_schemas() -> None:
    predictions = pd.DataFrame(
        [
            {
                "ticker": "AAA",
                "date": pd.Timestamp("2026-01-02", tz="UTC"),
                "stale_data_flag": False,
                "prob_down": 0.2,
                "prob_flat": 0.3,
                "prob_up": 0.5,
                "direction": "UP",
                "expected_return": 0.01,
                "predicted_volatility": 0.2,
                "confidence": "high",
                "top_features": [{"name": "log_return_1d", "shap_value": 0.2}],
            }
        ]
    )
    forecast = build_forecast_output(predictions, model_version="v0.1.0", horizon="1d", regime="low_vol")
    evidence = build_evidence_bundle(
        forecast_id=forecast["forecast_id"],
        features=pd.DataFrame([{"ticker": "AAA", "date": pd.Timestamp("2026-01-02", tz="UTC"), "log_return_1d": 0.1}]),
        macro=pd.DataFrame([{"series_id": "VIXCLS", "available_at": pd.Timestamp("2026-01-02", tz="UTC"), "value": 20.0}]),
        model_name="lightgbm_multiclass_calibrated",
        model_version="v0.1.0",
        trained_at=pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        training_samples=100,
        stale_tickers=[],
        source_metadata={
            "requested_source": "dummy",
            "used_source": "dummy",
            "dummy_mode": "null_random_walk",
            "fallback_used": False,
            "fallback_reason": None,
            "attempt_errors": [],
            "as_of_time": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        },
        hyperparameters={"n_estimators": 200, "calibration_method": "multinomial_logistic"},
        feature_importance=[{"feature": "log_return_1d", "mean_abs_shap": 0.4}],
        calibration_summary={"enabled": True, "method": "multinomial_logistic", "samples": 32},
        drift_summary={"max_psi": 0.12, "mean_psi": 0.05, "warning_features": [], "critical_features": []},
        regime_summary={
            "method": "gaussian_hmm",
            "current_regime": "low_vol",
            "previous_regime": "low_vol",
            "dominant_recent_regime": "low_vol",
            "regime_shift_flag": False,
            "state_probability": 0.8,
            "transition_rate": 0.0,
            "reason": "ok",
        },
        retraining_monitor={"should_retrain": False, "trigger_count": 0, "triggers": []},
    )
    backtest = {
        "backtest_id": forecast["forecast_id"],
        "config": {
            "model_name": "lightgbm_multiclass_calibrated",
            "model_version": "v0.1.0",
            "start_date": "2024-01-01",
            "end_date": "2025-12-31",
            "horizon": "1d",
            "initial_train_days": 756,
            "eval_days": 63,
            "embargo_days": 2,
            "feature_version": "v0.1.0",
            "universe": "synthetic-sp500",
            "portfolio_rule": {
                "strategy_name": "classified_directional",
                "probability_threshold": 0.35,
                "top_bucket_fraction": 0.25,
                "bottom_bucket_fraction": 0.25,
                "holding_days": 5,
                "min_edge": 0.02,
                "bucket_hysteresis": 1.0,
                "hysteresis_edge_buffer": 0.02,
                "reentry_cooldown_days": 3,
                "max_turnover_per_day": 0.04,
                "participation_volume_floor": 0.75,
                "participation_volume_ceiling": 1.25,
            },
        },
        "completed_at": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        "folds": [],
        "aggregate_metrics": {
            "hit_rate_mean": 0.4,
            "hit_rate_std": 0.01,
            "log_loss_mean": 1.0,
            "brier_score_mean": 0.62,
            "ece_mean": 0.05,
            "calibration_gap_mean": 0.03,
            "ic_mean": 0.02,
            "rank_ic_mean": 0.03,
            "ece_warning_breach_count": 2,
            "ece_warning_breach_ratio": 0.5,
            "calibration_gap_warning_breach_count": 1,
            "calibration_gap_warning_breach_ratio": 0.25,
        },
        "cost_adjusted_metrics": {
            "information_ratio": 0.2,
            "sharpe_ratio": 0.2,
            "sortino_ratio": 0.3,
            "max_drawdown": -0.1,
            "calmar_ratio": 0.4,
            "annual_return": 0.05,
            "gross_annual_return": 0.08,
            "annual_volatility": 0.2,
            "avg_daily_turnover": 0.1,
            "total_cost_bps": 20.0,
            "active_days_ratio": 0.35,
            "signal_days_ratio": 0.35,
            "two_sided_signal_days_ratio": 0.12,
            "one_sided_signal_days_ratio": 0.23,
            "avg_gross_exposure": 0.4,
            "avg_selected_names": 2.0,
            "selection_stability": 0.4,
            "cost_drag_annual_return": 0.03,
            "gross_information_ratio": 0.3,
            "gross_positive_day_ratio": 0.52,
            "net_positive_day_ratio": 0.5,
            "rebalance_thinned_days_ratio": 0.2,
            "avg_liquidity_multiplier": 1.0,
            "avg_target_turnover": 0.08,
        },
        "portfolio_rule_analysis": {
            "classification_hit_rate_mean": 0.4,
            "selected_rule": {
                "strategy_name": "classified_directional",
                "probability_threshold": 0.35,
                "top_bucket_fraction": 0.25,
                "bottom_bucket_fraction": 0.25,
                "holding_days": 5,
                "min_edge": 0.02,
                "bucket_hysteresis": 1.0,
                "hysteresis_edge_buffer": 0.02,
                "reentry_cooldown_days": 3,
                "max_turnover_per_day": 0.04,
                "metrics": {"information_ratio": 0.2, "active_days_ratio": 0.35, "selection_stability": 0.4},
            },
            "uncontrolled_selected_rule": {
                "strategy_name": "classified_directional",
                "probability_threshold": 0.35,
                "top_bucket_fraction": 0.25,
                "bottom_bucket_fraction": 0.25,
                "holding_days": 5,
                "metrics": {"information_ratio": 0.15, "avg_daily_turnover": 0.15, "cost_drag_annual_return": 0.05, "selection_stability": 0.3},
            },
            "control_effect": {
                "information_ratio_delta": 0.05,
                "avg_daily_turnover_delta": -0.05,
                "cost_drag_annual_return_delta": -0.02,
                "selection_stability_delta": 0.1,
                "rebalance_thinned_days_ratio": 0.2,
            },
            "legacy_two_sided_rule": {
                "strategy_name": "classified_two_sided",
                "probability_threshold": 0.4,
                "top_bucket_fraction": 0.2,
                "bottom_bucket_fraction": 0.2,
                "holding_days": 1,
                "metrics": {"information_ratio": 0.0, "active_days_ratio": 0.0},
            },
            "best_cpcv_candidate": {"name": "classified_directional_thr_0.35_top_0.25_bottom_0.25_hold_5"},
            "candidate_family_summary": {"holding_rule_analysis": []},
            "primary_reasons": ["Legacy two-sided classification rule left most days flat, so classification hit rate could not monetize."],
        },
        "pbo": 0.25,
        "cpcv": {
            "splits": [
                {
                    "split_id": 1,
                    "train_start": "2024-01-01",
                    "train_end": "2025-01-31",
                    "test_start": "2025-02-01",
                    "test_end": "2025-03-31",
                    "n_train": 100,
                    "n_test": 20,
                    "best_candidate": {"name": "thr_0.40_bucket_0.20"},
                    "best_candidate_test_information_ratio": 0.1,
                    "best_candidate_test_active_days_ratio": 0.35,
                    "best_candidate_test_selection_stability": 0.4,
                    "best_candidate_oos_rank_percentile": 0.66,
                    "best_candidate_logit_omega": 0.7,
                }
            ],
            "aggregate_metrics": {"hit_rate_mean": 0.4, "log_loss_mean": 1.0, "ece_mean": 0.05, "information_ratio_mean": 0.1},
            "candidate_strategies": [
                {
                    "name": "classified_directional_thr_0.35_top_0.25_bottom_0.25_hold_5",
                    "strategy_name": "classified_directional",
                    "probability_threshold": 0.35,
                    "top_bucket_fraction": 0.25,
                    "bottom_bucket_fraction": 0.25,
                    "holding_days": 5,
                    "mean_oos_information_ratio": 0.1,
                    "mean_oos_gross_information_ratio": 0.12,
                    "mean_oos_annual_return": 0.05,
                    "mean_oos_gross_annual_return": 0.08,
                    "mean_oos_cost_drag_annual_return": 0.03,
                    "mean_oos_active_days_ratio": 0.35,
                    "mean_oos_signal_days_ratio": 0.35,
                    "mean_oos_avg_daily_turnover": 0.1,
                    "mean_oos_total_cost_bps": 20.0,
                    "mean_oos_selection_stability": 0.4,
                    "mean_oos_two_sided_signal_days_ratio": 0.12,
                    "mean_oos_one_sided_signal_days_ratio": 0.23,
                    "mean_oos_rebalance_thinned_days_ratio": 0.2,
                    "mean_oos_avg_target_turnover": 0.08,
                }
            ],
            "cluster_candidate_strategies": [
                {
                    "cluster_name": "classified_directional_thr_cluster_0.30-0.35_bucket_cluster_top=0.25|bottom=0.25_hold_cluster_3-5",
                    "strategy_name": "classified_directional",
                    "threshold_cluster_key": "0.30-0.35",
                    "bucket_cluster_key": "top=0.25|bottom=0.25",
                    "holding_days_cluster_key": "3-5",
                    "member_count": 2,
                    "member_names": [
                        "classified_directional_thr_0.30_top_0.25_bottom_0.25_hold_3",
                        "classified_directional_thr_0.35_top_0.25_bottom_0.25_hold_5",
                    ],
                    "mean_oos_information_ratio": 0.1,
                    "mean_oos_gross_information_ratio": 0.12,
                    "mean_oos_annual_return": 0.05,
                    "mean_oos_cost_drag_annual_return": 0.03,
                    "mean_oos_active_days_ratio": 0.35,
                    "mean_oos_selection_stability": 0.4,
                }
            ],
            "portfolio_rule_summary": {"holding_rule_analysis": [], "bucket_analysis": [], "threshold_analysis": [], "strategy_analysis": []},
            "cluster_adjusted_splits": [
                {
                    "split_id": 1,
                    "best_cluster": {"cluster_name": "x"},
                    "runner_up_cluster": {"cluster_name": "y"},
                }
            ],
            "cluster_adjusted_pbo": 0.1,
            "cluster_adjusted_pbo_summary": {
                "definition": "x",
                "label": "low_overfit_risk",
                "detail": "x",
                "thresholds": {"low": 0.2, "moderate": 0.5, "high": 0.8},
            },
            "cluster_adjusted_pbo_diagnostics": {
                "near_candidate_competition": {
                    "competition_dominated": False,
                    "dominant_axis": "threshold",
                    "dominant_value": "0.30-0.35",
                    "close_split_ratio": 0.5,
                }
            },
            "pbo_summary": {
                "definition": "x",
                "label": "moderate_overfit_risk",
                "detail": "x",
                "thresholds": {"low": 0.2, "moderate": 0.5, "high": 0.8},
            },
        },
        "diebold_mariano": {
            "vs_baseline": "class_prior",
            "dm_statistic": 0.0,
            "p_value": 1.0,
        },
        "feature_importance_summary": [{"feature": "log_return_1d", "mean_abs_shap": 0.4}],
        "model_comparison": [
            {
                "model_name": "xgboost_multiclass_calibrated",
                "model_version": "v0.1.0",
                "status": "completed",
                "aggregate_metrics": {"hit_rate_mean": 0.39, "log_loss_mean": 1.01, "ece_mean": 0.06},
                "cost_adjusted_metrics": {"information_ratio": 0.18},
                "diebold_mariano": {"vs_baseline": "class_prior", "dm_statistic": 0.0, "p_value": 1.0},
                "comparison_to_primary": {
                    "hit_rate_mean_delta": -0.01,
                    "log_loss_mean_delta": 0.01,
                    "ece_mean_delta": 0.01,
                    "information_ratio_delta": -0.02,
                },
            }
        ],
        "drift_monitor": {
            "bucket_count": 10,
            "warning_threshold": 0.2,
            "critical_threshold": 0.25,
            "family_thresholds": {
                "price_momentum": {"warning": 0.2, "critical": 0.25},
                "macro": {"warning": 0.3, "critical": 0.45},
            },
            "max_psi": 0.12,
            "mean_psi": 0.05,
            "max_raw_psi": 0.2,
            "mean_raw_psi": 0.08,
            "stable_feature_ratio": 0.9,
            "warning_features": [],
            "critical_features": [],
            "feature_groups": [{"group": "macro", "feature_count": 4, "max_psi": 0.12, "mean_psi": 0.05, "flagged_features": []}],
            "supplementary_analysis": {
                "primary_cause": "stable",
                "proxy_ohlcv_used": False,
                "regime_active": False,
                "proxy_sensitive_flagged_features": [],
                "non_proxy_flagged_features": [],
                "macro_volatility_flagged_features": [],
                "raw_to_adjusted_reduction_mean": 0.1,
                "feature_diagnostics": [
                    {
                        "feature": "log_return_1d",
                        "raw_psi": 0.12,
                        "adjusted_psi": 0.12,
                        "family": "price_momentum",
                        "proxy_sensitive": False,
                        "primary_cause": "stable",
                        "retrain_action": "ignore",
                        "status": "PASS",
                    }
                ],
                "notes": [],
            },
            "features": [
                {
                    "feature": "log_return_1d",
                    "feature_family": "price_momentum",
                    "warning_threshold": 0.2,
                    "critical_threshold": 0.25,
                    "proxy_sensitive": False,
                    "raw_psi": 0.12,
                    "psi": 0.12,
                    "stability_transform": "identity",
                    "stability_reduction": 0.0,
                    "mean_shift_sigma": 0.0,
                    "analysis_tag": "stable",
                    "primary_cause": "stable",
                    "retrain_action": "ignore",
                    "status": "PASS",
                }
            ],
        },
        "regime_monitor": {
            "method": "gaussian_hmm",
            "current_regime": "low_vol",
            "previous_regime": "low_vol",
            "dominant_recent_regime": "low_vol",
            "regime_shift_flag": False,
            "state_probability": 0.8,
            "transition_rate": 0.0,
            "reason": "ok",
        },
        "retraining_monitor": {
            "base_should_retrain": False,
            "should_retrain": False,
            "trigger_count": 0,
            "triggers": [],
            "observations": [],
            "drift_signal": {
                "weighted_score": 0.0,
                "weighted_threshold": 1.5,
                "immediate_threshold": 2.5,
                "trigger_feature_count": 0,
                "trigger_family_count": 0,
                "persistent": False,
                "triggered": False,
                "family_scores": {},
                "family_feature_counts": {},
                "trigger_families": [],
                "suppressed_families": [],
                "suppressed_feature_count": 0,
            },
            "calibration_signal": {
                "ece_mean": 0.05,
                "calibration_gap_mean": 0.03,
                "ece_breach_count": 2,
                "ece_breach_ratio": 0.5,
                "calibration_gap_breach_count": 1,
                "calibration_gap_breach_ratio": 0.25,
                "minimum_persistent_folds": 2,
                "minimum_breach_ratio": 0.4,
                "immediate_multiplier": 1.5,
                "ece_warning_threshold": 0.05,
                "calibration_gap_warning_threshold": 0.05,
                "ece_persistent": True,
                "calibration_gap_persistent": False,
                "ece_triggered": True,
                "calibration_gap_triggered": False,
            },
            "policy_decision": "watch_only",
            "policy_notes": [],
            "cooloff_active": False,
            "cooloff_reference_date": None,
            "cooloff_remaining_business_days": 0,
            "base_trigger_names": [],
            "effective_trigger_names": [],
            "suppressed_trigger_names": [],
            "history_lookback_count": 0,
        },
    }
    risk = build_risk_review(forecast["forecast_id"], forecast, backtest, max_drawdown_limit=0.15)
    report = build_report_payload(forecast, backtest, risk)
    assert "approval_notes" in risk
    assert risk["approval_notes"]
    assert "retraining_monitor" in risk
    paper_batch = {
        "batch_id": forecast["forecast_id"],
        "forecast_id": forecast["forecast_id"],
        "created_at": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        "forecast_date": "2026-01-02",
        "week_id": "2026-W01",
        "ledger_path": "outputs/paper_trading/trade_ledger.parquet",
        "approval": "MANUAL_REVIEW_REQUIRED",
        "should_retrain": False,
        "metrics": {
            "new_trades": 1,
            "queued_trades_this_run": 1,
            "executed_trades_this_run": 0,
            "settled_trades_this_run": 0,
            "pending_trades_total": 1,
            "queued_trades_total": 1,
            "settled_trades_total": 0,
            "skipped_trades_total": 0,
            "liquidity_capped_trades_this_run": 0,
            "liquidity_blocked_trades_this_run": 0,
            "avg_participation_rate": 0.01,
            "avg_round_trip_cost_bps": 20.0,
        },
        "execution_diagnostics": {
            "intended_trades": 1,
            "attempted_trades": 0,
            "filled_trades": 0,
            "partial_fills": 0,
            "missed_trades": 0,
            "fill_rate": 0.0,
            "partial_fill_rate": 0.0,
            "missed_trade_rate": 0.0,
            "realized_vs_intended_exposure": 0.0,
            "execution_cost_drag": 0.0,
            "execution_cost_drag_bps": 0.0,
            "gap_slippage_bps": 0.0,
        },
        "trades": [
            {
                "trade_id": forecast["forecast_id"],
                "ticker": "AAA",
                "direction": "UP",
                "confidence": "high",
                "prob_up": 0.5,
                "prob_down": 0.2,
                "prob_flat": 0.3,
                "expected_return": 0.01,
                "expected_trade_return": 0.01,
                "expected_net_return": 0.008,
                "predicted_volatility": 0.2,
                "stale_data_flag": False,
                "signal_time": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
                "execution_time": pd.Timestamp("2026-01-05T14:30:00Z").isoformat(),
                "signal_reference_price": 100.0,
                "execution_price": None,
                "status": "QUEUED",
                "target_notional": 50000.0,
                "executed_notional": 0.0,
                "intended_order_quantity": 500.0,
                "filled_quantity": 0.0,
                "unfilled_quantity": 500.0,
                "unfilled_notional": 50000.0,
                "fillable_notional_cap": 10000.0,
                "adv_dollar_volume": 1000000.0,
                "participation_rate": 0.0,
                "fill_rate": 0.0,
                "partial_fill": False,
                "missed_trade": False,
                "liquidity_capped": False,
                "liquidity_blocked": False,
                "round_trip_cost_bps": 20.0,
                "gap_slippage_bps": 0.0,
                "execution_cost_drag": 0.0,
                "execution_reason": "queued_for_next_open",
            }
        ],
    }
    weekly_review = {
        "review_id": forecast["forecast_id"],
        "week_id": "2026-W01",
        "generated_at": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        "window_start": "2025-12-29",
        "window_end": "2026-01-02",
        "summary": "x",
        "metrics": {
            "total_trades": 1,
            "settled_trades": 0,
            "pending_trades": 1,
            "queued_trades": 0,
            "skipped_trades": 0,
            "hit_rate": None,
            "avg_realized_return": None,
            "avg_gross_trade_return": None,
            "avg_net_trade_return": None,
            "avg_expected_return": 0.01,
            "avg_expected_net_return": 0.008,
            "avg_round_trip_cost_bps": 20.0,
            "avg_participation_rate": 0.01,
            "liquidity_capped_trades": 0,
            "liquidity_blocked_trades": 0,
            "retraining_batches": 0,
        },
        "execution_diagnostics": {
            "intended_trades": 1,
            "attempted_trades": 1,
            "filled_trades": 1,
            "partial_fills": 0,
            "missed_trades": 0,
            "fill_rate": 1.0,
            "partial_fill_rate": 0.0,
            "missed_trade_rate": 0.0,
            "realized_vs_intended_exposure": 1.0,
            "execution_cost_drag": 0.002,
            "execution_cost_drag_bps": 20.0,
            "gap_slippage_bps": 5.0,
        },
        "approval_breakdown": {"MANUAL_REVIEW_REQUIRED": 1},
    }
    retraining_event = {
        "event_id": forecast["forecast_id"],
        "forecast_id": forecast["forecast_id"],
        "created_at": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        "week_id": "2026-W01",
        "approval": "MANUAL_REVIEW_REQUIRED",
        "regime": "low_vol",
        "max_psi": 0.12,
        "ece_mean": 0.05,
        "pbo": 0.25,
        "pbo_label": "moderate_overfit_risk",
        "trigger_count": 1,
        "triggers": [{"name": "pbo", "status": "WARNING", "detail": "x"}],
        "action": "retrain_before_next_production_style_run",
    }
    validate_payload("forecast_output", forecast)
    validate_payload("evidence_bundle", evidence)
    validate_payload("risk_review", risk)
    validate_payload("report_payload", report)
    validate_payload("backtest_result", backtest)
    validate_payload("paper_trading_batch", paper_batch)
    validate_payload("weekly_review", weekly_review)
    validate_payload("retraining_event", retraining_event)
    monitor_audit = {
        "audit_id": forecast["forecast_id"],
        "dataset_type": "public_real_market",
        "generated_at": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        "window": {"start_date": "2024-01-01", "end_date": "2025-12-31", "horizon": "1d"},
        "data_sources": {
            "source_mode": "live",
            "ohlcv_source": "fred_market_proxy",
            "proxy_ohlcv_used": True,
            "macro_source": "fred_csv",
            "fallback_used": False,
            "fallback_reason": None,
            "dummy_mode": None,
            "ohlcv_transport": {"origins": ["network"], "cache_used": False, "snapshot_used": False},
            "macro_transport": {"origins": ["cache"], "cache_used": True, "snapshot_used": False},
        },
        "universe": ["SPY", "QQQ"],
        "backtest": {
            "backtest_id": forecast["forecast_id"],
            "hit_rate_mean": 0.4,
            "ece_mean": 0.05,
            "information_ratio": 0.2,
            "pbo": 0.25,
            "pbo_summary": {"label": "moderate_overfit_risk"},
            "cluster_adjusted_pbo": 0.1,
            "cluster_adjusted_pbo_summary": {"label": "low_overfit_risk"},
            "portfolio_rule_analysis": {
                "selected_rule": {"strategy_name": "classified_directional"},
                "primary_reasons": ["x"],
            },
        },
        "drift_monitor": {"max_psi": 0.12},
        "regime_monitor": {"current_regime": "low_vol"},
        "retraining_monitor": {"should_retrain": False, "trigger_count": 0, "triggers": [], "observations": []},
        "paper_trading_summary": {
            "batch_id": forecast["forecast_id"],
            "approval": "MANUAL_REVIEW_REQUIRED",
            "avg_round_trip_cost_bps": 20.0,
            "avg_participation_rate": 0.01,
            "liquidity_capped_trades_this_run": 0,
            "liquidity_blocked_trades_this_run": 0,
            "execution_diagnostics": {
                "fill_rate": 0.9,
                "partial_fill_rate": 0.1,
                "missed_trade_rate": 0.0,
                "realized_vs_intended_exposure": 0.9,
                "execution_cost_drag": 0.003,
                "gap_slippage_bps": 7.0,
            },
            "weekly_execution_diagnostics": {
                "fill_rate": 0.9,
                "partial_fill_rate": 0.1,
                "missed_trade_rate": 0.0,
                "realized_vs_intended_exposure": 0.9,
                "execution_cost_drag": 0.003,
                "gap_slippage_bps": 7.0,
            },
        },
        "notes": ["x"],
    }
    validate_payload("monitor_audit", monitor_audit)
    monitor_audit_suite = {
        "suite_id": forecast["forecast_id"],
        "generated_at": pd.Timestamp("2026-01-02", tz="UTC").isoformat(),
        "dataset_type": "public_real_market",
        "profile_name": "fast",
        "profile_role": "development_smoke",
        "analysis_mode": "live_suite",
        "as_of_dates": ["2026-01-02", "2026-01-03"],
        "ticker_sets": [["SPY", "QQQ"], ["SPY", "GLD"]],
        "run_count": 2,
        "cpcv_max_splits": 2,
        "runs": [
            {
                "audit_id": forecast["forecast_id"],
                "backtest_id": forecast["forecast_id"],
                "as_of_date": "2026-01-02",
                "ticker_set": "SPY,QQQ",
                "information_ratio": 0.2,
                "pbo": 0.25,
                "pbo_label": "moderate_overfit_risk",
                "cluster_adjusted_pbo": 0.1,
                "cluster_adjusted_pbo_label": "low_overfit_risk",
                "candidate_pbo_competition_dominated": True,
                "pbo_competition_dominated": False,
                "candidate_pbo_dominant_axis": "threshold",
                "pbo_dominant_axis": "threshold",
                "candidate_pbo_dominant_value": "0.35",
                "pbo_dominant_value": "0.35",
                "candidate_pbo_close_competition_ratio": 1.0,
                "pbo_close_competition_ratio": 0.5,
                "selection_stability": 0.4,
                "hit_rate_mean": 0.4,
                "base_should_retrain": False,
                "should_retrain": False,
                "policy_decision": "watch_only",
                "base_trigger_names": [],
                "trigger_names": [],
                "suppressed_trigger_names": [],
                "policy_notes": [],
            }
        ],
        "distribution_summary": {
            "information_ratio": {"count": 1, "mean": 0.2, "median": 0.2, "std": 0.0, "min": 0.2, "max": 0.2},
            "pbo": {"count": 1, "mean": 0.25, "median": 0.25, "std": 0.0, "min": 0.25, "max": 0.25},
            "cluster_adjusted_pbo": {"count": 1, "mean": 0.1, "median": 0.1, "std": 0.0, "min": 0.1, "max": 0.1},
            "selection_stability": {"count": 1, "mean": 0.4, "median": 0.4, "std": 0.0, "min": 0.4, "max": 0.4},
            "base_retraining_rate": 0.0,
            "retraining_rate": 0.0,
            "base_trigger_counts": {},
            "effective_trigger_counts": {},
            "policy_decision_counts": {"watch_only": 1},
            "pbo_competition_dominated_rate": 0.0,
            "candidate_pbo_competition_dominated_rate": 1.0,
            "pbo_dominant_axis_counts": {"threshold": 1},
            "candidate_pbo_dominant_axis_counts": {"threshold": 1},
        },
        "by_ticker_set": [],
        "by_as_of_date": [],
    }
    validate_payload("monitor_audit_suite", monitor_audit_suite)
